title: Mingxuan Liu's Homepage
page-top-title: Mingxuan Liu
top-section-bg-text: Medical Image Analysis
home-subtitle: Mingxuan Liu&ensp;|&ensp;刘铭轩
copyright-text: '&copy; Mingxuan Liu 2023-2026. All Rights Reserved.'
